openapi: 3.0.0
info:
  version: 1.0.0
  title: Currency API

paths:
  /currencies:
    get:
      tags:
        - "Currencies"
      summary: Get all currencies
      responses:
        '200':
          $ref: '#/components/responses/Success200'
        '404':
          $ref: '#/components/responses/NotFound404'
        '500':
          $ref: '#/components/responses/Error500'
    put:
      tags:
        - "Currencies"
      summary: Update a currency
      requestBody:
        description: Currency data to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyInput'
      responses:
        '204':
          $ref: '#/components/responses/Success204'
        '404':
          $ref: '#/components/responses/NotFound404'
        '500':
          $ref: '#/components/responses/Error500'

  /currencies/{id}:
    get:
      tags:
        - "Currencies"
      summary: Get a currency by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the currency
      responses:
        '200':
          $ref: '#/components/responses/Success200'
        '404':
          $ref: '#/components/responses/NotFound404'
        '500':
          $ref: '#/components/responses/Error500'

  /accounts:
    get:
      tags:
        - "Accounts"
      summary: Get all accounts
      responses:
        '200':
          $ref: '#/components/responses/Success200'
        '404':
          $ref: '#/components/responses/NotFound404'
        '500':
          $ref: '#/components/responses/Error500'
  /accounts/{id}:
    get:
      summary: Get an account by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the account
      responses:
        '200':
          $ref: '#/components/responses/Success200'
        '404':
          $ref: '#/components/responses/NotFound404'
        '500':
          $ref: '#/components/responses/Error500'


components:
  responses:
    Success200:
      description: Successful response
      content:
        application/json:
          example:
            id: 1
            name: Euro
            code: EUR
    Success204:
      description: Successful update, no content

    NotFound404:
      description: Resource not found
      content:
        application/json:
          example:
            error: Currency not found

    Error500:
      description: Internal server error
      content:
        application/json:
          example:
            error: Internal server error
  schemas:
    CurrencyInput:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
